[package]
name = "laputa_core"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
path = "lib.rs"

[dependencies]
thiserror.workspace = true
snowdon.workspace = true
url.workspace = true
cookie.workspace = true